"""
Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

"""


from math import sqrt
from lib.timer import best_time

def pentagonal_generator(n=1): 
    while True:
        yield (n*(3*n-1))//2
        n += 1


def ispentagonal(n):
    x = sqrt(24*n+1)+1
    return x//6 == x/6 and x//6 > 0

def solve():
    P = [None] # P[i] = ith pentagonal number

    for n in pentagonal_generator():
        previous = reversed(P[1:])
        for p in previous:
            if ispentagonal(n-p) and ispentagonal(n+p):
                return n-p
        P.append(n)

if __name__ == '__main__':
    print(best_time(solve))

