"""
Triangular, pentagonal, and hexagonal
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
    Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
    Hexagonal       Hn=n(2n−1)          1, 6, 15, 28, 45, ...

    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.

"""

# best to go over Hexagonals as they are larger
# 

from math import sqrt

def hexagonals(n=144): 
    while True:
        yield n*(2*n-1)
        n += 1


def ispentagonal(n):
    x = sqrt(24*n+1)+1
    return x//6 == x/6 and x//6 > 0

def istriangle(n):
    x = sqrt(2*n + .25)+.5
    return x == int(x) and x > 0


def solve():
    for h in hexagonals():
        if istriangle(h) and ispentagonal(h):
            return h
            

if __name__ == '__main__':
    print(solve())





